<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=edge"/>
<title>Test results - Class specs.SpecsFixture</title>
<link href="../css/base-style.css" rel="stylesheet" type="text/css"/>
<link href="../css/style.css" rel="stylesheet" type="text/css"/>
<script src="../js/report.js" type="text/javascript"></script>
</head>
<body>
<div id="content">
<h1>Class specs.SpecsFixture</h1>
<div class="breadcrumbs">
<a href="../index.html">all</a> &gt; 
<a href="../packages/specs.html">specs</a> &gt; SpecsFixture</div>
<div id="summary">
<table>
<tr>
<td>
<div class="summaryGroup">
<table>
<tr>
<td>
<div class="infoBox" id="tests">
<div class="counter">1</div>
<p>tests</p>
</div>
</td>
<td>
<div class="infoBox" id="failures">
<div class="counter">1</div>
<p>failures</p>
</div>
</td>
<td>
<div class="infoBox" id="ignored">
<div class="counter">0</div>
<p>ignored</p>
</div>
</td>
<td>
<div class="infoBox" id="duration">
<div class="counter">33m24.58s</div>
<p>duration</p>
</div>
</td>
</tr>
</table>
</div>
</td>
<td>
<div class="infoBox failures" id="successRate">
<div class="percent">0%</div>
<p>successful</p>
</div>
</td>
</tr>
</table>
</div>
<div id="tabs">
<ul class="tabLinks">
<li>
<a href="#tab0">Failed tests</a>
</li>
<li>
<a href="#tab1">Tests</a>
</li>
<li>
<a href="#tab2">Standard output</a>
</li>
</ul>
<div id="tab0" class="tab">
<h2>Failed tests</h2>
<div class="test">
<a name="[Concordion Specification for 'SpecsFixture"></a>
<h3 class="failures">[Concordion Specification for 'SpecsFixture</h3>
<span class="code">
<pre>org.concordion.internal.ConcordionAssertionError: Specification has failure(s). See output HTML for details.
	at org.concordion.internal.FixtureState$3.assertIsSatisfied(FixtureState.java:105)
	at org.concordion.internal.SummarizingResultRecorder.assertIsSatisfied(SummarizingResultRecorder.java:50)
	at org.concordion.internal.FixtureRunner.printResultSummary(FixtureRunner.java:54)
	at org.concordion.internal.FixtureRunner.run(FixtureRunner.java:43)
	at org.concordion.integration.junit4.ConcordionRunner$1.evaluate(ConcordionRunner.java:125)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.concordion.integration.junit4.ConcordionRunner.runChild(ConcordionRunner.java:115)
	at org.concordion.integration.junit4.ConcordionRunner.runChild(ConcordionRunner.java:21)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre>
</span>
</div>
</div>
<div id="tab1" class="tab">
<h2>Tests</h2>
<table>
<thead>
<tr>
<th>Test</th>
<th>Duration</th>
<th>Result</th>
</tr>
</thead>
<tr>
<td class="failures">[Concordion Specification for 'SpecsFixture</td>
<td>33m24.58s</td>
<td class="failures">failed</td>
</tr>
</table>
</div>
<div id="tab2" class="tab">
<h2>Standard output</h2>
<span class="code">
<pre>test: ?[34m[INFO ]?[0;39m 12:06:34 ?[36mo.c.ext.run.parallel?[0;39m - Running concordion:run commands in parallel with 5 threads

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/response/HealthResponse.html
Successes: 3, Failures: 0

test: ?[34m[INFO ]?[0;39m 12:06:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:06:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:06:50 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (java.net.SocketTimeoutException) caught when processing request to {}-&gt;http://slowwly.robertomurray.co.uk:80: Read timed out
test: ?[34m[INFO ]?[0;39m 12:06:50 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {}-&gt;http://slowwly.robertomurray.co.uk:80
test: ?[34m[INFO ]?[0;39m 12:06:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:06:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:06:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:06:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:06:59 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:06:59 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:00 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (java.net.SocketTimeoutException) caught when processing request to {}-&gt;http://slowwly.robertomurray.co.uk:80: Read timed out
test: ?[34m[INFO ]?[0;39m 12:07:00 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {}-&gt;http://slowwly.robertomurray.co.uk:80
test: ?[34m[INFO ]?[0;39m 12:07:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:07:09 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:09 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:10 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (java.net.SocketTimeoutException) caught when processing request to {}-&gt;http://slowwly.robertomurray.co.uk:80: Read timed out
test: ?[34m[INFO ]?[0;39m 12:07:10 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {}-&gt;http://slowwly.robertomurray.co.uk:80
test: ?[34m[INFO ]?[0;39m 12:07:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:19 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:19 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/util/HttpRequestUtil.html
Successes: 3, Failures: 0

test: ?[1;31m[ERROR]?[0;39m 12:07:20 ?[36mi.n.u.ResourceLeakDetector?[0;39m - LEAK: You are creating too many HashedWheelTimer instances.  HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.
test: ?[34m[INFO ]?[0;39m 12:07:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:07:29 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:29 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:30 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:30 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:07:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:07:39 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:39 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:39 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:39 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:40 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:40 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:07:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:07:49 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:49 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:49 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:49 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:50 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:50 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:07:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:07:59 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:07:59 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:08:09 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:09 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:10 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:10 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:08:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:08:19 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:19 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:19 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:19 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:20 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:20 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:08:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:08:29 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:29 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:29 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:29 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:30 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:30 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:08:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:08:39 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:39 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/response/CtpJsonResponse.html
Successes: 0, Failures: 0, Exceptions: 6

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/response/Responses.html
Successes: 0, Failures: 0, Exceptions: 4

test: ?[34m[INFO ]?[0;39m 12:08:45 ?[36ms.s.ScheduledJobShortFixture?[0;39m - Wait up to 39 seconds for scheduled job to run
test: ?[34m[INFO ]?[0;39m 12:08:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/multitenancy/paypal/Authorization2.html
Successes: 2, Failures: 1, Exceptions: 3

test: ?[34m[INFO ]?[0;39m 12:08:50 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:50 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:08:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:08:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:09:00 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:00 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:09:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:09:10 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:10 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/scheduler/ScheduledJobShort2.html
Successes: 7, Failures: 2

test: ?[34m[INFO ]?[0;39m 12:09:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:09:30 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:30 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:09:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:09:40 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:40 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:09:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:09:50 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:09:50 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/multitenancy/creditcard/ChargeImmediatelyWithout3ds2.html
Successes: 0, Failures: 0, Exceptions: 19

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/multitenancy/Multitenancy.html
Successes: 2, Failures: 1, Exceptions: 22

test: ?[34m[INFO ]?[0;39m 12:10:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:10:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:10:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:10:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:10:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:10:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:10:40 ?[36ms.s.ScheduledJobShortFixture?[0;39m - Wait up to 38 seconds for scheduled job to run
test: ?[34m[INFO ]?[0;39m 12:10:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:10:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:10:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:10:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:11:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:11:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/scheduler/ScheduledJobShort.html
Successes: 7, Failures: 2, Exceptions: 2

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/scheduler/ScheduledJobs.html
Successes: 14, Failures: 4, Exceptions: 2

test: ?[34m[INFO ]?[0;39m 12:11:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:11:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:11:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:11:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:11:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:11:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:12:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:12:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:12:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:12:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:12:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:12:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:12:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:12:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:12:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:12:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:13:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:13:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:13:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:13:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:13:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:13:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:13:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:13:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:14:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:14:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:14:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:14:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:14:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:14:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:14:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:14:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:14:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:14:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:15:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:15:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:15:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:15:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:15:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:15:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:15:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:15:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:16:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:16:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:16:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:16:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:16:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:16:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:16:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:16:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:16:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:16:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:17:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:17:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/creditcard/AuthorizationWithout3ds.html
Successes: 0, Failures: 0, Exceptions: 21

test: ?[34m[INFO ]?[0;39m 12:17:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:17:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:17:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:17:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:17:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:17:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:17:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:17:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:17:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:17:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:17:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:17:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:18:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:18:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:18:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:18:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:18:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:18:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/response/I18nPayoneResponse.html
Successes: 0, Failures: 0, Exceptions: 12

test: ?[34m[INFO ]?[0;39m 12:18:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:18:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:18:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:18:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:18:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:19:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:19:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/creditcard/AuthorizationWith3ds.html
Successes: 0, Failures: 0, Exceptions: 20

test: ?[34m[INFO ]?[0;39m 12:19:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:19:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:19:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:19:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:19:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:19:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/creditcard/ChargeImmediatelyWithout3ds.html
Successes: 0, Failures: 0, Exceptions: 23

test: ?[34m[INFO ]?[0;39m 12:20:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:20:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:18 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:20:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:25 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:25 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:20:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:20:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:20:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:20:58 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:21:03 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:03 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:04 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:05 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:05 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:08 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:21:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:28 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:21:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:38 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:21:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:44 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:45 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:45 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:45 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:45 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://api.pay1.de:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:48 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://api.pay1.de:443
test: ?[34m[INFO ]?[0;39m 12:21:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:54 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:21:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:21:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/creditcard/ChargeImmediatelyWith3ds.html
Successes: 0, Failures: 0, Exceptions: 23

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/creditcard/Creditcard.html
Successes: 0, Failures: 0, Exceptions: 87

test: ?[1;31m[ERROR]?[0;39m 12:22:06 ?[36ms.p.s.ChargeImmediatelyFixture?[0;39m - [Payment 1, Payment 3, Payment 4] payments are not re-directed - the notifications [appointed] won't come
test: ?[31m[WARN ]?[0;39m 12:22:07 ?[36ms.p.s.ChargeImmediatelyFixture?[0;39m - Previous txAction [appointed] was not success: expected 3, but found 0. Waiting for [paid] action is skipped!
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/sofortueberweisung/ChargeImmediately.html
Successes: 6, Failures: 21, Exceptions: 4

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/sofortueberweisung/Sofortueberweisung.html
Successes: 6, Failures: 21, Exceptions: 4

test: ?[34m[INFO ]?[0;39m 12:22:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:14 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:24 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:25 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:25 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:25 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:25 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:34 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/cashinadvance/Preauthorization.html
Successes: 0, Failures: 0, Exceptions: 4

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/paypal/Authorization.html
Successes: 4, Failures: 3, Exceptions: 8

test: ?[34m[INFO ]?[0;39m 12:22:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:22:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:22:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:03 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:03 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:03 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:03 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:05 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:05 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:15 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:35 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:43 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:45 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:45 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:53 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:23:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:23:55 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:24:03 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:24:03 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/paypal/ChargeImmediately.html
Successes: 5, Failures: 3, Exceptions: 8

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/paypal/Paypal.html
Successes: 9, Failures: 6, Exceptions: 16

test: ?[34m[INFO ]?[0;39m 12:24:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:24:13 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:24:13 ?[36ms.p.k.KlarnaRequest?[0;39m - Start waiting 900 seconds for 2 notifications of action [appointed] for payments [b8d98aa7-2068-4399-8547-975354b59761, 62234c1b-e39c-4c95-bd5e-2dd880be9e23] in [KlarnaRequest] test:
test: ?[34m[INFO ]?[0;39m 12:24:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:24:23 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:24:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - I/O exception (org.apache.http.conn.ConnectionPoolTimeoutException) caught when processing request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443: Timeout waiting for connection from pool
test: ?[34m[INFO ]?[0;39m 12:24:33 ?[36mo.a.h.i.e.RetryExec?[0;39m - Retrying request to {s}-&gt;https://ct-payone-integration-staging.herokuapp.com:443
test: ?[34m[INFO ]?[0;39m 12:24:43 ?[36ms.p.c.CustomerPaymentFixture?[0;39m - Start waiting 900 seconds for 4 notifications of action [appointed] for payments [921ced73-91db-4765-a2df-808a3c53ead1, 241be02a-520d-4498-a595-6152d5ea5f12, afd67ba5-7c60-4094-b3c5-76d1e95f0433, d5be544a-6829-4183-9069-a09b0982a60d] in [CustomerPaymentFixture] test:
test: ?[34m[INFO ]?[0;39m 12:27:18 ?[36ms.p.k.KlarnaRequest?[0;39m - Intermediate report: waited 184/900 sec, received 0/2 notifications of action [appointed] in test [KlarnaRequest]
test: ?[34m[INFO ]?[0;39m 12:27:50 ?[36ms.p.c.CustomerPaymentFixture?[0;39m - Intermediate report: waited 186/900 sec, received 0/4 notifications of action [appointed] in test [CustomerPaymentFixture]
test: ?[34m[INFO ]?[0;39m 12:30:21 ?[36ms.p.k.KlarnaRequest?[0;39m - Intermediate report: waited 367/900 sec, received 0/2 notifications of action [appointed] in test [KlarnaRequest]
test: ?[34m[INFO ]?[0;39m 12:30:55 ?[36ms.p.c.CustomerPaymentFixture?[0;39m - Intermediate report: waited 371/900 sec, received 0/4 notifications of action [appointed] in test [CustomerPaymentFixture]
test: ?[34m[INFO ]?[0;39m 12:33:23 ?[36ms.p.k.KlarnaRequest?[0;39m - Intermediate report: waited 550/900 sec, received 0/2 notifications of action [appointed] in test [KlarnaRequest]
test: ?[34m[INFO ]?[0;39m 12:34:01 ?[36ms.p.c.CustomerPaymentFixture?[0;39m - Intermediate report: waited 557/900 sec, received 0/4 notifications of action [appointed] in test [CustomerPaymentFixture]
test: ?[34m[INFO ]?[0;39m 12:36:26 ?[36ms.p.k.KlarnaRequest?[0;39m - Intermediate report: waited 733/900 sec, received 0/2 notifications of action [appointed] in test [KlarnaRequest]
test: ?[34m[INFO ]?[0;39m 12:37:07 ?[36ms.p.c.CustomerPaymentFixture?[0;39m - Intermediate report: waited 743/900 sec, received 0/4 notifications of action [appointed] in test [CustomerPaymentFixture]
test: ?[1;31m[ERROR]?[0;39m 12:39:14 ?[36ms.p.k.KlarnaRequest?[0;39m - Failure waited 900 seconds to receive 0/2 notifications of action [appointed] for payments b8d98aa7-2068-4399-8547-975354b59761, 62234c1b-e39c-4c95-bd5e-2dd880be9e23 in KlarnaRequest test
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/klarna/KlarnaRequest.html
Successes: 10, Failures: 5, Exceptions: 8

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/klarna/Klarna.html
Successes: 10, Failures: 5, Exceptions: 8

test: ?[1;31m[ERROR]?[0;39m 12:39:57 ?[36ms.p.c.CustomerPaymentFixture?[0;39m - Failure waited 913 seconds to receive 0/4 notifications of action [appointed] for payments 921ced73-91db-4765-a2df-808a3c53ead1, 241be02a-520d-4498-a595-6152d5ea5f12, afd67ba5-7c60-4094-b3c5-76d1e95f0433, d5be544a-6829-4183-9069-a09b0982a60d in CustomerPaymentFixture test
test: ?[31m[WARN ]?[0;39m 12:39:57 ?[36ms.p.c.CustomerPaymentFixture?[0;39m - Previous txAction [appointed] was not success: expected 3, but found 0. Waiting for [paid] action is skipped!
/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/cashinadvance/CustomerPayment.html
Successes: 2, Failures: 16, Exceptions: 4

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/cashinadvance/Cashinadvance.html
Successes: 2, Failures: 16, Exceptions: 8

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/paymentmethods/Paymentmethods.html
Successes: 27, Failures: 48, Exceptions: 123

/home/travis/build/commercetools/commercetools-payone-integration/functionaltests/build/reports/spec/specs/Specs.html
Successes: 49, Failures: 53, Exceptions: 169

</pre>
</span>
</div>
</div>
<div id="footer">
<p>
<div>
<label class="hidden" id="label-for-line-wrapping-toggle" for="line-wrapping-toggle">Wrap lines
<input id="line-wrapping-toggle" type="checkbox" autocomplete="off"/>
</label>
</div>Generated by 
<a href="http://www.gradle.org">Gradle 3.4.1</a> at Nov 3, 2017 12:39:59 PM</p>
</div>
</div>
</body>
</html>
